### ISSUE TITLE
Handlevogn produktoversikt - kontroller

### ISSUE THREAD

**Issue by aleanon** [aleanon/Nettside-kafe#13]
Lage initiel fil for kontroller funksjoner med følgende funksjonalitet:

- oppdatere antall ønskede av hvert produkt.
- ~~fjerne produkter~~
- Endre kommentar på hvert produkt
- gå til neste steg
- ~~fortsette å handle~~

**Comment by JohnF-Get** [comment]
Man kan nå fjerne produkter og fortsette og handle.
