### ISSUE TITLE
Adminside: Lagerbeholdning

### ISSUE THREAD

**Issue by JohnF-Get** [aleanon/Nettside-kafe#22]
En produktliste som viser antall varer på lageret. Antall kan oppdateres av bruker.

**Comment by JohnF-Get** [comment]
https://github.com/aleanon/Nettside-kafe/blob/main/src/admin/lagerbeholdning.html

**Comment by aleanon** [comment]
Nå er modellen den samme på klient siden og admin siden, men for å få produktene, må man først gå inn på klient siden.

Dersom man går rett på admin siden uten å ha noe i localStorage får man ikke noen produkter i modellen.
