### ISSUE TITLE
Finne en måte a lagre endringer på modellen.

### ISSUE THREAD

**Issue by JohnF-Get** [aleanon/Nettside-kafe#23]
Vi må finne en måte å lagre beholdningen. Hvordan blir det når en ansatt oppdater beholdningen (unitsInStock), eller et produkt er tomt på lageret.  Hvordan kan vi ha modellen dynamisk da? Setter en "kritisk" label på dette siden alle visninger av produkter er avhengig av lagerbeholding.

**Comment by JohnF-Get** [comment]
pinger @vardaasen @Kenneth-Jakobsen @aleanon

**Comment by JohnF-Get** [comment]
Jeg tenker å bruke  `localStorage.getItem` og `localStorage.setItem` på adminsider (enkel innloggingsfunksjonalitet). 

Kanskje vi kan bruke localStorage for `product` og de andre objekter som vi trenger å være persistent. Jeg skal prøve/leke med dette på lagerbeholding og bestillingersside i admin-seksjonen.

**Comment by aleanon** [comment]
Har laget en versjon som bruker node.js som server. Har fått api til å fungere, men parkerer denne intil det eventuelt blir relevant
