### ISSUE TITLE
Bug: Feil på app diven

### ISSUE THREAD

**Issue by aleanon** [aleanon/Nettside-kafe#33]
Elementer som legges til etter app diven i index.html dukker opp inne i app diven

**Comment by JohnF-Get** [comment]
## Test: Reproduksjon av bug

### kode:
 ![Image](https://github.com/user-attachments/assets/023e522d-94c8-4de8-9009-a4e9fba2c569)

### skjermbilde
![Image](https://github.com/user-attachments/assets/b6182a24-c8af-4b15-856b-b551cadad693)
