### ISSUE TITLE
Skjul produkter som ikke er på lager

### ISSUE THREAD

**Issue by aleanon** [aleanon/Nettside-kafe#44]
Enten skjul eller grå ut produkter som ikke er igjen på lager

**Comment by JohnF-Get** [comment]
Som diskutert, går vi på greyed-out løsning. Jeg kan jobbe med CSS for dette, og en liten conditional i js i kveld.

**Comment by JohnF-Get** [comment]
Implementert. Tøm local storage for å se endring.
