### ISSUE TITLE
Rydde i struktur

### ISSUE THREAD

**Issue by aleanon** [aleanon/Nettside-kafe#45]
Det begynner å bli mange filer og forskjell på struktur for admin siden og bruker siden. 
Her må vi bli enige om en måte som er felles for begge og refaktorere.

**Comment by JohnF-Get** [comment]
Forslag:

src/
├── index.html
├── admin/
│   ├── index.html
│   ├── bestillinger.html
│   └── lagerbeholdning.html
├── assets/
│   ├── css/
│   │   ├── styles.css
│   │   ├── variables.css
│   │   ├── modern-normalize.css
│   │   ├── base/
│   │   ├── layout/
│   │   ├── components/
│   │   └── state/
│   ├── img/
│   └── js/
│   │   ├── common.js
│   │   ├── model.js
│   │   ├── view.js
package.json
eslint.config.mjs

**Comment by JohnF-Get** [comment]
Etter prat i stad,  er det 2 måter å gjøre dette synes jeg. Jeg liker alternativ #2, da jobber man per funksjonalitet

### Alternativ 1

/src
  ├── index.html
  ├── /css
  │   ├── base
  │   ├── layout
  │   ├── components
  │   ├── state
  │   └── theme
  ├── /js
  │   ├── /controllers
  │   │   ├── cafeMenuController.js
  │   │   ├── cakeMenuController.js
  │   │   ├── cartController.js
  │   │   ├── orderController.js
  │   │   └── controller.js
  │   ├── /models
  │   │   └── model.js
  │   ├── /views
  │   │   ├── cafeMenuView.js
  │   │   ├── cakeMenuView.js
  │   │   ├── cartView.js
  │   │   ├── orderView.js
  │   │   └── view.js
  │   └── /utils
  │       └── serverRequests.js
  ├── /img
  │   ├── cafe_menu/
  │   └── cakes/
  ├── /store
  │   └── products.json
  ├── /tests
  │   └── unitTestExample.js
package.json

### Alternativ 2

/src
  ├── index.html
  ├── /css
  │   ├── base
  │   ├── layout
  │   ├── components
  │   ├── state
  │   └── theme
  ├── /js
  │   ├── /products
  │   │   ├── cafeMenuController.js
  │   │   ├── cafeMenuView.js
  │   │   ├── cakeMenuController.js
  │   │   ├── cakeMenuView.js
  │   ├── /cart
  │   │   ├── cartController.js
  │   │   ├── cartView.js
  │   ├── /order
  │   │   ├── orderController.js
  │   │   ├── orderView.js
  │   ├── /shared
  │   │   ├── view.js
  │   │   ├── controller.js
  │   │   └── model.js
  │   └── /utils
  │       └── serverRequests.js
  ├── /img
  │   ├── cafe_menu/
  │   └── cakes/
  ├── /store
  │   └── products.json
  ├── /tests
  │   └── unitTestExample.js

**Comment by JohnF-Get** [comment]
sgenerelt er store-mappen faktisk veldig god mappenavn fordi json er ment til å bli oppdatert - (store som lager), men det er forvirrende i vårt prosjekt siden vi jobber med en nettbutikk (store) , da kan vi bruke data som mappa for json-filen.
