### ISSUE TITLE
Undersøke libphonenumber-js

### ISSUE THREAD

**Issue by vardaasen** [aleanon/Nettside-kafe#63]
Se på libphonenumber-js , for pålitelig validering av telefonnummer heller en egendefinert regex for varlidering

**Comment by JohnF-Get** [comment]
Ser ut som vi ikke har tid til dette for beta. Gjenåpne hvis du vil jobbe med dette senere, eller kanskje vi kan ikke forbedre nettstedet etter beta lenger.
